# YAML 

# GitHub Actions Workflow YAML

name: CI python 3 A
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - install:
	pip install --upgrade pip &&\
       	pip install -r requirements.txt

      - test:
        python -m pytest -vv test_hello.py

      - format:
        black *.py

      - lint:
      	pylint --disable=R,C hello.py

      - all: install lint test
