# YAML 

# GitHub Actions Workflow YAML

name: CI python 3 A
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Install dependencies
       run: |
        pip install -r requirements.txt

     - name: Run tests
       run: |
        python -m pytest 

     - name: Format code with black
       run: |
        black *.py

     - name: Lint with pylint
       run: |
         pylint --disable=R,C hello.py
